export const FETCH_ISSUES_REQUEST = 'FETCH_ISSUES_REQUEST';
export const FETCH_ISSUES_FAILURE = 'FETCH_ISSUES_FAILURE';
export const FETCH_ISSUES_SUCCESS = 'FETCH_ISSUES_SUCCESS';
export const FETCH_ISSUE_DETAILS_REQUEST = 'FETCH_ISSUE_DETAILS_REQUEST';
export const FETCH_ISSUE_DETAILS_FAILURE = 'FETCH_ISSUE_DETAILS_FAILURE';
export const FETCH_ISSUE_DETAILS_SUCCESS = 'FETCH_ISSUE_DETAILS_SUCCESS';